#!/usr/bin/env bash

set -Eeo pipefail

PORT_NAME="${1:-/dev/ttyUSB0}"
ROS_DISTRO_SETUP="/opt/ros/humble/setup.bash"
OMY_SETUP="/home/chan/omy_franka_teleop/open_manipulator_omy/install/setup.bash"

source "${ROS_DISTRO_SETUP}"
source "${OMY_SETUP}"
set -u

echo "Starting OMY teleop on ${PORT_NAME}"
exec ros2 launch open_manipulator_bringup \
  omy_l100_leader_ai.launch.py \
  port_name:="${PORT_NAME}"
